# Enable C++ support
language: cpp

addons:
  apt:
    packages:
      - cmake
      - libgsl0-dev
      - libfftw3-3
      - libccfits-dev
      - libnfft3-dev
      - libarmadillo-dev
      - libboost-all-dev
      - catch
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - libomp
      - gsl
      - fftw
      - brewsci/science/ccfits
      - cfitsio
      - brewsci/science/nfft
      - armadillo
      - boost
      - catch2

matrix:
  include:
    - os: linux
      name: "GNU/Linux with GCC"
    - os: osx
      name: "macOS with AppleClang"
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - *macos_packages
    - os: osx
      name: "macOS with vanilla Clang"
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
      addons:
        homebrew:
          packages:
            - llvm
            - *macos_packages

cache:
    directories:
      - /home/travis/build/CosmoStat/Glimpse/build/SPARSE2D
      - /home/travis/build/CosmoStat/Glimpse/build/NICAEA

before_install:
  - eval "${MATRIX_EVAL}"

install: true

# Build steps
script:
    - mkdir -p build && cd build
    - cmake -DBUILD_TESTING=ON ..
    - make
    - ./glimpse --version
